#!/usr/bin/env bash
# Copies buddy's face into SystemUI for patch 0015.
#
#   scripts/vendor-face.sh            # copy into $BUDDY_TREE
#   scripts/vendor-face.sh --check    # fail if the tree's copy is out of date
#
# SystemUI draws the lock screen in its own process and cannot call into buddy, so the
# few files that draw the face have to exist on both sides. They are written and tested
# in core/android (FaceGeometryTest, LockFaceTest); this copies them across and rewrites
# the package, so there is one definition and one generated copy rather than two files
# drifting apart. Never edit the copy in the tree.
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

CHECK=0
[[ "${1:-}" == "--check" ]] && CHECK=1

SRC="$BUDDY_SRC/core/android/src/main/kotlin/buddy/android/surface"
DEST="$BUDDY_TREE/frameworks/base/packages/SystemUI/src/com/android/systemui/buddy"
PACKAGE="com.android.systemui.buddy"

FILES=(
    "creature/FaceGeometry.kt"
    "creature/CreatureState.kt"
    "creature/FacePainter.kt"
    "lockscreen/LockFace.kt"
    "lockscreen/BuddyFaceView.kt"
)

# One package in the tree, so the imports between them go away with it.
rewrite() {
    local file="$1"
    printf '// Generated by platform/scripts/vendor-face.sh from core/android. Do not edit here:\n'
    printf '// the original is %s, and it is compiled and tested in that repo.\n' "$2"
    sed -e "s|^package .*|package $PACKAGE|" \
        -e "/^import buddy\.android\.surface\.\(creature\|lockscreen\)\./d" \
        -e "s|buddy\.android\.surface\.creature\.||g" \
        -e "s|buddy\.android\.surface\.lockscreen\.||g" \
        "$file"
}

status=0
for rel in "${FILES[@]}"; do
    src="$SRC/$rel"
    [[ -f "$src" ]] || die "missing $src"
    out="$DEST/$(basename "$rel")"
    if [[ $CHECK -eq 1 ]]; then
        if ! diff -q <(rewrite "$src" "surface/$rel") "$out" >/dev/null 2>&1; then
            log "OUT OF DATE: $out"
            status=1
        fi
    else
        mkdir -p "$DEST"
        rewrite "$src" "surface/$rel" > "$out"
        log "vendored $(basename "$rel")"
    fi
done

if [[ $CHECK -eq 1 ]]; then
    [[ $status -eq 0 ]] && log "the tree's copy of the face is current" || die "run scripts/vendor-face.sh"
else
    log "the face is in $DEST"
    log "SystemUI's Android.bp must list that directory in its srcs; see patches/README.md 0015"
fi
